// RootLayout.js ou _app.js
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./componentes/menu";
import NextAuthSessionProvider from '@/providers/sessionProvider';
import { UserProvider } from '@/providers/userProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <UserProvider>
            <div className="conteiner">
              <div className="flex-grow">
                {children}
              </div>
            </div>
          </UserProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
