
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./componentes/menu"
import NextAuthSessionProvider from '@/providers/sessionProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <NextAuthSessionProvider>
        <div className="conteiner">
            <div className="flex-grow">
              {children}
            </div>
        </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
