import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AiFillMessage } from "react-icons/ai";
import { FaRegCalendar } from "react-icons/fa";
import { HiMiniDocumentText } from "react-icons/hi2";
import { LuLayoutPanelLeft } from "react-icons/lu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="conteiner">
            <div className="menu">
              <Link href="/inicial" ><LuLayoutPanelLeft className="icon"/></Link>
              <Link href="/chat" ><AiFillMessage className="icon"/></Link>
              <Link href="/calendario" ><FaRegCalendar className="icon"/></Link>
              <Link href="/referencias" ><HiMiniDocumentText className="icon"/></Link>
            </div>
            <div className="flex-grow">
              {children}
            </div>
        </div>
      </body>
    </html>
  );
}
